stages:
  prepare:
    cmd: python cd_src/prepare.py
    deps:
      - cd_src/prepare.py
    outs:
      - data/raw

  # preprocess:
  #   cmd: python cd_src/preprocess.py
  #   deps:
  #     - data/raw
  #     - cd_src/preprocess.py
  #   outs:
  #     - data/processed

  # train:
  #   cmd: python cd_src/train.py
  #   deps:
  #     - data/processed
  #     - cd_src/train.py
  #   outs:
  #     - cd_models/autoencoder.h5

  # evaluate:
  #   cmd: python cd_src/evaluate.py
  #   deps:
  #     - cd_models/autoencoder.h5
  #     - cd_src/evaluate.py
  #   metrics:
  #     - cd_metrics/eval.txt
